name: Examples Extract to Google Sheets

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      SHEET_ID: ${{ secrets.SHEET_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build examples targets JSON
        env:
          STRICT_ENABLED: "0"
        run: |
          python -m pip install --quiet gspread google-auth
          python scripts/examples_to_targets_json.py
          echo '--- DEBUG: examples_targets.json length & first item ---'
          if [ -f config/examples_targets.json ]; then
            jq 'length' config/examples_targets.json || true
            jq '.[0]' config/examples_targets.json || true
          else
            echo 'config/examples_targets.json not found'
          fi
      - name: Install deps for extract
        run: |
          python -m pip install --quiet requests beautifulsoup4 lxml
      - name: Setup Playwright (browsers + deps)
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true
      - name: Install OCR deps (best-effort)
        run: |
          sudo apt-get update -y || true
          sudo apt-get install -y tesseract-ocr || true
          python -m pip install --quiet pillow pytesseract || true
      - name: Extract from examples (selectors-driven)
        run: |
          python -m src.run_extract config/examples_targets.json
      - name: Debug CSV outputs
        run: |
          ls -1 *.csv || true
          for f in *.csv; do echo "== $f =="; head -n 5 "$f"; break; done || true
      - name: Push CSVs to Google Sheets
        run: |
          python -m pip install --quiet gspread google-auth
          python scripts/push_to_sheet.py
