name: Quarterly Extract to Google Sheets

on:
  schedule:
    - cron: "0 0 1 1,4,7,10 *"  # UTC
  workflow_dispatch: {}

jobs:
  # 1) 秘密情報（シート認証）を使ってターゲットJSONを作成（アーティファクト化）
  prepare-targets:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build targets from Google Sheet
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          python -m pip install --quiet gspread google-auth
          python scripts/sheet_to_targets_json.py
      - name: Upload targets artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarterly-targets
          path: config/targets_flat.json

  # 2) 秘密情報を使わないジョブで matrix を生成（Outputs に安全に載せる）
  build-targets:
    needs: prepare-targets
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.mk.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: quarterly-targets
          path: config
      - id: mk
        shell: bash
        run: |
          python - <<'PY' > matrix.json
          import json
          with open('config/targets_flat.json', 'r', encoding='utf-8') as f:
              items = json.load(f)
          data = { 'include': [ {'id': i['id']} for i in items ] }
          print(json.dumps(data, ensure_ascii=False))
          PY
          matrix=$(cat matrix.json)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  run:
    needs: build-targets
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      # outputs.matrix が空のときでも fromJson が失敗しないようフォールバック
      matrix: ${{ fromJson((needs.build-targets.outputs.matrix != '' && needs.build-targets.outputs.matrix) || '{"include": []}') }}
    # matrix が空ならジョブ自体をスキップ
    if: ${{ needs.build-targets.outputs.matrix != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --quiet requests beautifulsoup4 lxml
      - name: Extract target
        env:
          TARGET_ID: ${{ matrix.id }}
        run: |
          python -m src.run_extract config/targets_flat.json "$TARGET_ID"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.id }}-csv
          path: ${{ matrix.id }}.csv

  push:
    needs: run
    runs-on: ubuntu-22.04
    # 実行ジョブがスキップ/失敗した場合はスキップ
    if: ${{ needs.run.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: out
      - name: Gather CSVs
        run: |
          shopt -s globstar; cp out/**/**/*.csv . || true
          ls -1 *.csv
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Push to Google Sheets
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          python -m pip install --quiet gspread google-auth
          python scripts/push_to_sheet.py
